name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: Spoonfish-Software/spoonfish-infra-templates/.github/workflows/worker-deploy.yml@main
    with:
      worker: spoonfish-landing-page
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
